# My first TensorFlow program

In [20]:
import tensorflow as tf
import numpy as np
print(tf.__version__)

1.10.0


## Adding two tensors

First, let's try doing this using numpy, the Python numericv package. numpy code is immediately evaluated

In [21]:
a = np.array([5,3,8])
b = np.array([3,-1,2])
c = np.add(a,b)
print(c)

[ 8  2 10]


The equivalent code in TensorFlow consists of two steps:

### Step 1: Build the graph

In [22]:
a = tf.constant([5,3,8])
b = tf.constant([3,-1,2])
c = tf.add(a,b)
#c = a + b
print(c)

Tensor("Add_14:0", shape=(3,), dtype=int32)


c is an Op ("Add") that returns a tensor of shape (3,) and holds int32. The shape is inferred from the computation graph.

### Step 2: Run the graph

In [23]:
with tf.Session() as sess:
    result = sess.run(c)
    print(result)

[ 8  2 10]


### Using a feed_dict

Same graph, but without hardcoding inputs at build stage

In [24]:
a = tf.placeholder(dtype = tf.int32, shape=(None,)) #batchsize x scalar
b = tf.placeholder(dtype=tf.int32, shape=(None,))
c = tf.add(a,b)
with tf.Session() as sess:
    result = sess.run(c, feed_dict={
        a: [3,4,5],
        b: [-1,2,3]
    })
    print(result)

[2 6 8]


## Use Heron's formula to calculate the area of a triangle

In [27]:
def compute_area(sides):
    # slice the input to get the sides
    a = sides[:,0] # 5.0, 2.3
    b = sides[:,1] # 3.0, 4.1
    c = sides[:,2] # 7.1, 4.8
    
    # Heron's formula
    s = (a+b+c) * 0.5 # (a+b) is a short-cut to tf.add(a,b)
    areasq = s * (s-a) * (s-b) * (s-c) # (a*b) is a short-cut to tf.multiply(a, b)
    return tf.sqrt(areasq)

with tf.Session() as sess:
    # pass in two triangles
    area = compute_area(tf.constant([
        [5.0, 3.0, 7.1],
        [2.3, 4.1, 4.8]
    ]))
    result = sess.run(area)
    print(result)
    

[6.278497 4.709139]


## Placeholder and feed_dict

In [29]:
with tf.Session() as sess:
    sides = tf.placeholder(tf.float32, shape=(None, 3)) # batchsize number of triangles, 3 sides
    area = compute_area(sides)
    result = sess.run(area, feed_dict={
        sides: [
            [5.0, 3.0, 7.1],
            [2.3, 4.1, 4.8]
        ]
    })
    print(result)

[6.278497 4.709139]
